// 등불지기 service worker (generated by vite.config.ts) — offline play
const CACHE = 'lanternkeeper-38be1435e9';
const PRECACHE = ["./","assets/Galmuri11-Bold-QdFGsJ3v.woff2","assets/Galmuri11-DfQIlyDK.woff2","assets/Galmuri9-B9HMP827.woff2","assets/archive-DsNV8G__.png","assets/atlas-0-D_HoE-pV.png","assets/atlas-1-Bvnzzlxg.png","assets/atlas-2-bw_fPR5N.png","assets/brik-Bghua_jS.png","assets/bundler-Bw4DLPZK.js","assets/index-BJUP2Lt5.css","assets/index-CLXkRnsX.js","assets/keeper-house-C6DnTPlO.png","assets/lantern-court-CQFM_a0I.png","assets/lume-BCdA_0Rl.png","assets/orin-fdf2HC-E.png","assets/player-common-0KVfSzX5.png","assets/resident-portraits-DpxGwgdx.png","assets/sanctuary-BbyqkECt.png","assets/town_dock-Df8peEQy.png","assets/town_dock_wide-DQwyKQk2.png","assets/transport-bc-Ej5BBV6A.js","assets/transport-peerjs-CT1w9YyM.js","icons/apple-touch-icon.png","icons/favicon-32.png","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","index.html","manifest.webmanifest"];
self.addEventListener('install', (e) => {
  // cache: 'reload' bypasses the HTTP cache so a fresh deploy never precaches a stale page
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('lanternkeeper-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // the page: network first, revalidated past the HTTP cache (updates show up at once), cached shell when offline
    e.respondWith(
      fetch(req, { cache: 'no-cache' })
        .catch(() => fetch(req))
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put('./', copy));
          }
          return res;
        })
        .catch(() => caches.match('./', { cacheName: CACHE }).then((r) => r || caches.match('index.html'))),
    );
    return;
  }
  // hashed assets, fonts, icons: cache first
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    })),
  );
});
