import { defineConfig, type Plugin } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';
import { createHash } from 'node:crypto';
import { readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

/** Files under public/ (copied verbatim to the build root), as POSIX paths. */
function publicFiles(dir = 'public'): string[] {
  const out: string[] = [];
  const walk = (d: string) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else out.push(relative(dir, p).split('\\').join('/'));
    }
  };
  try {
    walk(dir);
  } catch {
    // no public dir
  }
  return out;
}

/** Offline play: emit sw.js that precaches every built file (cache-first, network-first for the page). */
function serviceWorker(): Plugin {
  return {
    name: 'lanternkeeper-sw',
    apply: 'build',
    enforce: 'post',
    generateBundle(_opts, bundle) {
      const files = new Set<string>(['./', 'index.html']);
      for (const f of Object.keys(bundle)) if (!f.endsWith('.map')) files.add(f);
      for (const f of publicFiles()) if (f !== 'sw.js') files.add(f);
      const list = [...files].sort();
      const version = createHash('sha1').update(list.join('|')).digest('hex').slice(0, 10);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(version, list) });
    },
  };
}

function swSource(version: string, precache: string[]): string {
  return `// 등불지기 service worker (generated by vite.config.ts) — offline play
const CACHE = 'lanternkeeper-${version}';
const PRECACHE = ${JSON.stringify(precache)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('lanternkeeper-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // the page: network first (updates), cached shell when offline
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put('./', copy));
          }
          return res;
        })
        .catch(() => caches.match('./', { cacheName: CACHE }).then((r) => r || caches.match('index.html'))),
    );
    return;
  }
  // hashed assets, fonts, icons: cache first
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    })),
  );
});
`;
}

/** The single-file build is one self-contained HTML: drop links to PWA files it does not ship. */
function stripPwaLinks(): Plugin {
  return {
    name: 'lanternkeeper-strip-pwa',
    transformIndexHtml(html) {
      return html.replace(/\s*<link rel="(manifest|icon|apple-touch-icon)"[^>]*>/g, '');
    },
  };
}

// `vite build --mode single` produces one self-contained HTML file (fonts inlined)
// that can be opened directly from disk or published anywhere.
export default defineConfig(({ mode }) => ({
  base: './',
  plugins: mode === 'single' ? [viteSingleFile(), stripPwaLinks()] : [serviceWorker()],
  publicDir: mode === 'single' ? false : 'public',
  build: {
    outDir: mode === 'single' ? 'dist-single' : 'dist',
    assetsInlineLimit: mode === 'single' ? 100_000_000 : 4096,
    chunkSizeWarningLimit: 4000,
  },
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts'],
  },
}));
